name: Exploring Variables and Secrets
on: push
env:
    Container_Registry: docker.io
    Image_Name: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: |
                echo "docker build -t $Container_Registry/${{ vars.Docker_UserName }}/$Image_Name"
            - name: Docker Login
              run: |
                echo "docker login -u ${{ vars.Docker_UserName }} -p ${{ secrets.Docker_Password }}"
            - name: Docker Push
              run: |
                echo "docker push $Container_Registry/${{ vars.Docker_UserName }}/$Image_Name"
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
          - name: Docker Run
            run: |
              echo "docker run -d -p 8080:80 $Container_Registry/${{ vars.Docker_UserName }}/$Image_Name"                  


